#!/system/bin/sh


### Configure your options below ####


####################
#####  3D GPU  #####
####################

# Maximum 3D GPU clock
# Type 1 for > 200mhz
# Type 2 for > 228mhz
# Type 3 for > 267mhz (default)
# Type 4 for > 300mhz
# Type 5 for > 320mhz

# Enter the number you want below:

GPU_3D='3'


####################
#####  2D GPU  #####
####################

# Maximum 2D GPU clock
# Type 1 for > 200mhz
# Type 2 for > 228mhz (default)
# Type 3 for > 267mhz

# Enter the number you want below:

GPU_2D='2'


########################
#####  Sweep2Wake  #####
########################

# Sweep2Wake
# 0 = disabled (default)
# 1 = enabled
# 2 = enabled (with button backlight)

# Enter the number you want below:

SWEEP2WAKE='0'


###########################
###     Sweep2Wake      ###
###  Start-Stop Buttons ###
###########################

# Start button
# Type HOME > for HOME button (default)
# Type MENU > for MENU button
# Type BACK > BACK button

# Enter the number you want below:

SWEEP_START='HOME'

# End button
# Type SEARCH > for SEARCH button (default)
# Type BACK > BACK button
# Type MENU > for MENU button

# Enter the number you want below:

SWEEP_END='SEARCH'


#####################################################################################
#               DON'T EDIT ANYTHING BELOW THESE LINE                                #
#####################################################################################




























#####################################################################################
#               SERIOUSLY...........GO BACK UP !!!!                                 #
#####################################################################################


L="log -p i -t Kernel-init.d"


#Config Max 3D clock
case "$GPU_3D" in
1)
    chmod 644 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    echo 200000000 > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    $L "Maximum 3D gpu clock was set to:  `cat /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk`"
;;
2)
    chmod 644 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    echo 228571000 > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    $L "Maximum 3D gpu clock was set to:  `cat /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk`"
;;
3)
    chmod 644 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    echo 266667000 > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    $L "Maximum 3D gpu clock was set to:  `cat /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk`"
;;
4)
    chmod 644 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    echo 300000000 > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    $L "Maximum 3D gpu clock was set to:  `cat /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk`"
;;
5)
    chmod 644 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    echo 320000000 > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    $L "Maximum 3D gpu clock was set to:  `cat /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk`"
;;
esac

#Config Max 2D clock
case "$GPU_2D" in
1)
    chmod 644 /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk
    chmod 644 /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/max_gpuclk
    echo 200000000 > /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk
    echo 200000000 > /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/max_gpuclk
    $L "Maximum 2D gpu clock was set to:  `cat /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk`"
;;
2)
    chmod 644 /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk
    chmod 644 /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/max_gpuclk
    echo 228571000 > /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk
    echo 228571000 > /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/max_gpuclk
    $L "Maximum 2D gpu clock was set to:  `cat /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk`"
;;
3)
    chmod 644 /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk
    chmod 644 /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/max_gpuclk
    echo 266667000 > /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk
    echo 266667000 > /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/max_gpuclk
    $L "Maximum 2D gpu clock was set to:  `cat /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk`"
;;
esac


#Config Sweep2Wake
case "$SWEEP2WAKE" in
0)
    chmod 664 /sys/android_touch/sweep2wake
    echo 0 > /sys/android_touch/sweep2wake
    $L "Sweep2Wake was set to: `cat /sys/android_touch/sweep2wake` (disabled)"
;;
1)
    chmod 664 /sys/android_touch/sweep2wake
    echo 1 > /sys/android_touch/sweep2wake
    $L "Sweep2Wake was set to: `cat /sys/android_touch/sweep2wake` (enabled - buttons light)"
;;
2)
    chmod 664 /sys/android_touch/sweep2wake
    echo 2 > /sys/android_touch/sweep2wake
    $L "Sweep2Wake was set to: `cat /sys/android_touch/sweep2wake` (enabled - with buttons light)"
;;
esac

#Config Sweep2Wake buttons

if [ "$SWEEP2WAKE" > 0 ]
then

chmod 664 /sys/android_touch/sweep2wake_startbutton
chmod 664 /sys/android_touch/sweep2wake_endbutton

echo "$SWEEP_START" > /sys/android_touch/sweep2wake_startbutton
$L "Sweep2Wake start button was set to: `cat /sys/android_touch/sweep2wake_startbutton`"
echo "$SWEEP_END" > /sys/android_touch/sweep2wake_endbutton
$L "Sweep2Wake end button was set to: `cat /sys/android_touch/sweep2wake_endbutton`"

fi
